<a href="https://colab.research.google.com/github/MoseAIML/Moses-/blob/main/Recurrent_Neural_Networks_with_Python_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color='#2F4F4F'>Recurrent Neural Networks with Python - Project</font>

## <font color='#2F4F4F'>Step 1. Business Understanding </font>

### a) Specifying the Research Question

Build a recurrent neural networks model that will be used to predict Tesla stock prices in 2017 using data from 2012-2016

### b) Defining the Metric for Success

Build a neural networks regression model with an RSME  less than 10% of the target mean.

### c) Understanding the Context 

Stockpy is an innovative fintech enabling financial prosperity for the entire population. It is a venture funded startup based in Palo Alto bringing world-class financial experiences to a continually growing customer base. As Stockpy enters an expansion phase for innovative fintech product offerings, it aims to enhance the enormous value in data processing and analysis for continuous growth and success.

As a Finance Data Scientist for Stockpy, you provide leadership to turn cutting-edge technology into actionable insights; unlocking the power of data that provides value to business decisions and customer service enhancements.

### d) Recording the Experimental Design

* Business Understanding
* Data Exploration
* Data Preparation
* Data Modeling and Evaluation
* Summary of Findings and Recommendation
* Challenging the Solution


## <font color='#2F4F4F'>Step 2. Data Importation</font>

In [1]:
# Importing standard libraries
import pandas as pd               # library for data manipulation
import numpy as np                # library for scientific computations
import matplotlib.pyplot as plt   # library for data visualisation


In [3]:
# Importing our dataset
# Dataset URL (Train): https://bit.ly/3mVu0fw
#  Dataset URL (Test): https://bit.ly/361OMmQ 
#  https://bit.ly/3l0PQ0f

train_df = pd.read_csv('https://bit.ly/3mVu0fw')
train_df.head()


Date    Open    High     Low   Close      Volume
0  1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2  1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3  1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4  1/9/2012  322.04  322.29  309.46  620.76  11,688,800

## <font color='#2F4F4F'>Step 3. Data Exploration</font>

In [6]:
# Sample dataset
# ---
#
train_df.head()

Date    Open    High     Low   Close      Volume
0  1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2  1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3  1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4  1/9/2012  322.04  322.29  309.46  620.76  11,688,800

In [5]:
# Statistical summary
# ---
#
train_df.describe() 

Open         High          Low
count  1258.000000  1258.000000  1258.000000
mean    533.709833   537.880223   529.007409
std     151.904442   153.008811   150.552807
min     279.120000   281.210000   277.220000
25%     404.115000   406.765000   401.765000
50%     537.470000   540.750000   532.990000
75%     654.922500   662.587500   644.800000
max     816.680000   816.680000   805.140000

## <font color='#2F4F4F'>Step 4. Data Preparation</font>

In [7]:
# Getting our train dataset
# ---
#
train_set = train_df.iloc[:, 1:2].values
print(train_set)

[[325.25]
 [331.27]
 [329.83]
 ...
 [793.7 ]
 [783.33]
 [782.75]]


In [8]:
# Performing Feature scaling
# ---
#
from sklearn.preprocessing import MinMaxScaler
sc =  MinMaxScaler(feature_range = (0, 1))
train_set_scaled = sc.fit_transform(train_set)
print(train_set_scaled)

[[0.08581368]
 [0.09701243]
 [0.09433366]
 ...
 [0.95725128]
 [0.93796041]
 [0.93688146]]


In [9]:
# Creating a dataset with 60 timesteps and 1 output
# ---
#
X_train = []
y_train = []
for i in range(60, 1258):
    X_train.append(train_set_scaled[i-60:i, 0])
    y_train.append(train_set_scaled[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)

In [10]:
print(X_train)

[[0.08581368 0.09701243 0.09433366 ... 0.07846566 0.08034452 0.08497656]
 [0.09701243 0.09433366 0.09156187 ... 0.08034452 0.08497656 0.08627874]
 [0.09433366 0.09156187 0.07984225 ... 0.08497656 0.08627874 0.08471612]
 ...
 [0.92106928 0.92438053 0.93048218 ... 0.95475854 0.95204256 0.95163331]
 [0.92438053 0.93048218 0.9299055  ... 0.95204256 0.95163331 0.95725128]
 [0.93048218 0.9299055  0.93113327 ... 0.95163331 0.95725128 0.93796041]]


In [11]:
print(y_train)

[0.08627874 0.08471612 0.07454052 ... 0.95725128 0.93796041 0.93688146]


In [12]:
# Reshaping 
# ---
#
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

##  <font color='#2F4F4F'>Step 5. Data Modeling</font>

In [13]:
# Building the RNN
# ---
#
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

In [16]:
# Initialising the RNN
# ---
#
regressor = Sequential()

# Adding 4 LSTM layers and some Dropout regularisation
# ---
#


# Adding the output layer
# ---
#
regressor.add(LSTM(units = 50, return_sequences = True, input_shape = (X_train.shape[1], 1)))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

regressor.add(Dense(units = 1))

In [17]:
# Compile the RNN 
# ---
#
regressor.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [18]:
# Fitting the RNN to the training set
# ---
#
regressor.fit(X_train, y_train, epochs = 100, batch_size = 32)

Epoch 1/100
38/38 [==============================] - 9s 10ms/step - loss: 0.1330
Epoch 2/100
38/38 [==============================] - 0s 8ms/step - loss: 0.0875
Epoch 3/100
38/38 [==============================] - 0s 8ms/step - loss: 0.0837
Epoch 4/100
38/38 [==============================] - 0s 8ms/step - loss: 0.0814
Epoch 5/100
38/38 [==============================] - 0s 8ms/step - loss: 0.0806
Epoch 6/100
38/38 [==============================] - 0s 8ms/step - loss: 0.0794
Epoch 7/100
38/38 [==============================] - 0s 8ms/step - loss: 0.0789
Epoch 8/100
38/38 [==============================] - 0s 8ms/step - loss: 0.0791
Epoch 9/100
38/38 [==============================] - 0s 8ms/step - loss: 0.0793
Epoch 10/100
38/38 [==============================] - 0s 8ms/step - loss: 0.0779
Epoch 11/100
38/38 [==============================] - 0s 8ms/step - loss: 0.0777
Epoch 12/100
38/38 [==============================] - 0s 8ms/step - loss: 0.0781
Epoch 13/100
38/38 [================

In [19]:
# Making predictions: Getting the predicted stock price for 2017
# ---
#
test_df = pd.read_csv('https://bit.ly/361OMmQ')
test_df.head()

Date    Open    High     Low   Close     Volume
0  1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1  1/4/2017  788.36  791.34  783.16  786.90  1,073,000
2  1/5/2017  786.08  794.48  785.02  794.02  1,335,200
3  1/6/2017  795.26  807.90  792.20  806.15  1,640,200
4  1/9/2017  806.40  809.97  802.83  806.65  1,272,400

In [21]:
# Visualizing the results
# ---
#
real_stock_price = test_df.iloc[:, 1:2].values
print(real_stock_price)

[[778.81]
 [788.36]
 [786.08]
 [795.26]
 [806.4 ]
 [807.86]
 [805.  ]
 [807.14]
 [807.48]
 [807.08]
 [805.81]
 [805.12]
 [806.91]
 [807.25]
 [822.3 ]
 [829.62]
 [837.81]
 [834.71]
 [814.66]
 [796.86]]


In [22]:
dataset_total = pd.concat((train_df['Open'],
                           test_df['Open']), axis=0)

In [23]:
inputs = dataset_total[len(dataset_total)-len(test_df)-60:].values

In [24]:
inputs = inputs.reshape(-1, 1)

In [25]:
inputs = sc.transform(inputs)

In [26]:
# Then creating the test data structure just as we did for the train dataset
# ---
#
X_test = []
for i in range(60, 80):
    X_test.append(inputs[i-60:i, 0])
X_test = np.array(X_test)
X_test = np.reshape(X_test, (X_test.shape[0],
                    X_test.shape[1], 1))

In [27]:
# Making our Predictions
# ---
#
predicted_stock_price = regressor.predict(X_test)

1/1 [==============================] - 1s 643ms/step


In [ ]:
# Since we have predicted the scaled values, we reverse those values
# ---
#
predicted_stock_price = sc.inverse_transform(predicted_stock_price)
print(predicted_stock_price)

In [ ]:
# Model Evaluation
# ---
#
YOUR CODE GOES HERE

## <font color='#2F4F4F'>Step 6. Summary of Findings and Recommendation</font>

Your observation goes here...

## <font color='#2F4F4F'>Step 7. Challenging our Solution</font>

#### a) Did we have the right question?


#### b) Did we have the right data?


#### c) What can be done to improve the solution?
